### PR TITLE
Remove unused class NoodleDborCollection

### PR DESCRIPTION
**Pull request by cbeland**
This is at least a start cutting down on the proliferation of collection classes; I can't find anywhere in noodle-api or dbor_wip or dborutils where this is used.

### CODE REVIEW

**Comment by rivkahcarl** [comment]
@cbeland  just for some history. 
All these classes and code were used to migrate from mongo back to a relational db, in other words dbor. 
The reason we chose to not delete it right away when the migration was complete was in case we ever needed to pull data out of mongo and push elsewhere these classes would be used again.

**Comment by cbeland** [comment]
Ah, that explains this copy_service stuff; that should probably all be yanked out, too.

**Comment by noodle-tools** [comment]
@marcypetro has been assigned to review by @cbeland.

**Comment by noodle-tools** [comment]
Code review requested at 7ba428a by @cbeland. /cc @marcypetro

**Comment by cbeland** [comment]
https://app.asana.com/0/50576349521832/62177223882931
for the stuff this PR isn't getting.

**Comment by marcypetro** [comment]
Sweet! :+1:

**Comment by noodle-tools** [comment]
Code review approved to 7ba428a by @marcypetro. /cc @cbeland

**Comment by noodle-tools** [comment]
This code review has been closed. /cc @marcypetro @cbeland

**Pull request merged**
