### PR TITLE
Testing movement of Noodle Scrapy categorization

### PR DESCRIPTION
**Pull request by rivkahcarl**
Opening branch here to copy over noodle scrapy categorizing here so it can be used in dbor wip and then if successful for use, might want to keep here so can be available for multiple repos

### CODE REVIEW

**Comment by cbeland** [comment]
It would be greatly preferable to add noodle-scrapy as an external dependency than to copy-and-paste the category tree. If there are two copies, they will start to drift in different ways and cause problems.

If we don't want the entirety of noodle-scrapy as a dependency, I was thinking we might want to move shared code to dborutils, and make that a dependency of both noodle-scrapy and dbor_wip. I may need to do exactly that to share geo.py between the two repos.

**Comment by GeorgeNagel** [comment]
@cbeland I think that's the intention behind this branch. Move mutual code to dbor-utils.

**Comment by rivkahcarl** [comment]
yup spoke to @GeorgeNagel , im just playing around this this here,  to see how it can be effective within dbor and college majors and if it goes successfully, begin a discussion around if and how to move and try to start combining this with other DBOR enumerations as well. 
Allow for categorizing to happen in one place. 
It could be that with string categorizing for college majors, we might find other GQL expressions that are needed. etc

**Comment by cbeland** [comment]
Oh, sorry, I read this PR as being in dbor_wip, not dborutils. 8)

**Comment by remitaffin** [comment]
We are having proprietary code in this branch and the repo is public. I'm going to reset this branch to master and add a dummy commit so that we don't see this anymore.

**Comment by cbeland** [comment]
(Note that the code is still publicly accessible, since the commits are still in the repository - just no longer affiliated with any particular branch.)

**Comment by remitaffin** [comment]
@cbeland: where can we see those commits?

**Comment by cbeland** [comment]
Reading up on this...there are a few methods for undeleting branches:
http://stackoverflow.com/questions/2613903/does-deleting-a-branch-in-git-remove-it-from-the-history

However, it is also mentioned that commits no longer associated with a branch will be garbage-collected. I couldn't find anything from this branch using "git fsck" or git-resurrect.sh after a fresh clone, so I think we're as good as we can be given the branch was already pushed to origin and there's no guarantee someone didn't download it while it was up.

**Pull request closed without merging**
