### PR TITLE
Fix setup.py typos and update dependencies

### PR DESCRIPTION
**Pull request by cbeland**

### CODE REVIEW

**Comment by noodle-tools** [comment]
@jbradberry has been assigned to review by @cbeland.

**Comment by noodle-tools** [comment]
Code review requested at 693c140 by @cbeland. /cc @jbradberry

**Comment by noodle-tools** [comment]
@jbradberry has been assigned to review by @cbeland.

**Comment by noodle-tools** [comment]
Code review requested at 693c140 by @cbeland. /cc @jbradberry

**Comment by jbradberry** [comment]
@cbeland Ah, right, that last bit rings a bell.  Numpy is not particularly good about leaving up previous versions on pypi.

**Comment by noodle-tools** [comment]
Code review approved to 693c140 by @jbradberry. /cc @cbeland

**Comment by jbradberry** [comment]
Tentative acceptance, assuming that we don't care that numpy doesn't play well with others, and that we'll update the 0.4.4 tag to point to the merge commit after this lands.

**Comment by noodle-tools** [comment]
This code review has been closed. /cc @jbradberry @cbeland

**Comment by noodle-tools** [comment]
This code review has been closed. /cc @jbradberry @cbeland

**Comment by cbeland** [comment]
I agree with those assumptions.

**Pull request merged**
