### PR TITLE
Fix "SyntaxError: Non-ASCII character"

### PR DESCRIPTION
**Pull request by remitaffin**

### CODE REVIEW

**Comment by remitaffin** [comment]
Required for NoodleEducation/build#276

**Comment by noodle-tools** [comment]
@jbradberry has been assigned to review by @remitaffin.

**Comment by noodle-tools** [comment]
Code review requested at 21cc7c3 by @remitaffin. /cc @jbradberry

**Comment by jbradberry** [comment]
Oh, ha ha, I never explicitly approved.

"My name is Jeff Bradberry, and I approve this message."

**Pull request merged**
