### PR TITLE
Fix nice_key length

### PR DESCRIPTION
**Pull request by cbeland**
It was supposed to go to 2+10=12 but went to 2+8=10 in 0.4.4.

### CODE REVIEW

**Comment by cbeland** [comment]
After merging, this will need to be tagged 0.4.5.

**Comment by noodle-tools** [comment]
@jbradberry has been assigned to review by @cbeland.

**Comment by noodle-tools** [comment]
Code review requested at f018e47 by @cbeland. /cc @jbradberry

**Comment by noodle-tools** [comment]
Code review approved to f018e47 by @jbradberry. /cc @cbeland

**Comment by noodle-tools** [comment]
This code review has been closed. /cc @jbradberry @cbeland

**Pull request merged**
